services:
  database:
    image: 'postgres:latest'
    hostname: conductor-db
    ports:
      - 15432:5432
    env_file:
      - .env
    environment:
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_DB=${POSTGRES_DB}
    networks:
      - conductor-network
    volumes:
      - ${PWD}/postgresql/:/var/lib/postgresql/data/
  api:
    image: conductor:0.0.1
    hostname: conductor-api
    build:
      context: .
      dockerfile: Dockerfile 
    env_file:
      - .env
    environment:
      - PORT_NUMBER=${PORT_NUMBER}
      - DB_TYPE=${DB_TYPE}
      - CONNECTION_STRING=Server=conductor-db;Port=5432;Database=${POSTGRES_DB};User Id=${POSTGRES_USER};Password=${POSTGRES_PASSWORD};
      - SPLITTER_CHAR=${SPLITTER_CHAR}
      - ENABLE_LOG_DUMP=${ENABLE_LOG_DUMP}
      - LOG_DUMP_TIME_SEC=${LOG_DUMP_TIME_SEC}
      - ENCRYPT_KEY=${ENCRYPT_KEY}
      - SESSION_TIME_SEC=${SESSION_TIME_SEC}
      - API_KEY=${API_KEY}
      - MAX_DEGREE_PARALLEL=${MAX_DEGREE_PARALLEL}
      - MAX_CONSUMER_FETCH=${MAX_CONSUMER_FETCH}
      - MAX_CONSUMER_ATTEMPT=${MAX_CONSUMER_ATTEMPT}
      - MAX_PRODUCER_LINECOUNT=${MAX_PRODUCER_LINECOUNT}
      - LDAP_DOMAIN=${LDAP_DOMAIN}
      - LDAP_SERVER=${LDAP_SERVER}
      - LDAP_PORT=${LDAP_PORT}
      - LDAP_BASEDN=${LDAP_BASEDN}
      - LDAP_GROUPDN=${LDAP_GROUPDN}
      - LDAP_GROUPS=${LDAP_GROUPS}
      - LDAP_SSL=${LDAP_SSL}
      - LDAP_VERIFY_CERTIFICATE=${LDAP_VERIFY_CERTIFICATE}
      - NODES=${NODES}
      - USE_HTTPS=${USE_HTTPS}
      - TCP_ALLOWED_IPS=${TCP_ALLOWED_IPS}
      - HTTP_ALLOWED_IPS=${HTTP_ALLOWED_IPS}
      - ALLOWED_CORS=${ALLOWED_CORS}
      - BULK_TIMEOUT_SEC=${BULK_TIMEOUT_SEC}
      - DEVELOPMENT_MODE=${DEVELOPMENT_MODE}
      - DEBUG_DETAILED_ERROR=${DEBUG_DETAILED_ERROR}
      - CONNECTION_TIMEOUT_MIN=${CONNECTION_TIMEOUT_MIN}
      - MAX_CONCURRENT_CONNECTIONS=${MAX_CONCURRENT_CONNECTIONS}
      - RESPONSE_CACHING_LIMIT_MB=${RESPONSE_CACHING_LIMIT_MB}
      - MAX_LOG_QUEUE_SIZE=${MAX_LOG_QUEUE_SIZE}
      - REQUIRE_AUTHENTICATION=${REQUIRE_AUTHENTICATION}
    depends_on:
      - database
    networks:
      - conductor-network
    ports:
      - "22000:${PORT_NUMBER}"
  
networks:
  conductor-network:
    driver: bridge