// <auto-generated />
using System;
using Conductor.Data;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

#nullable disable

namespace Conductor.Migrations
{
    [DbContext(typeof(EfContext))]
    [Migration("20250209162434_Migration001")]
    partial class Migration001
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "9.0.1");

            modelBuilder.Entity("Conductor.Model.Destination", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "destinationConStr");

                    b.Property<string>("DbType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "destinationDbType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "destinationName");

                    b.Property<double>("TimeZoneOffSet")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "destinationTimeZoneOffSet");

                    b.HasKey("Id");

                    b.ToTable("DESTINATIONS");
                });

            modelBuilder.Entity("Conductor.Model.Extraction", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "extractionAlias");

                    b.Property<string>("BodyStructure")
                        .HasColumnType("TEXT");

                    b.Property<string>("Dependencies")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("DestinationId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("EndpointFullName")
                        .HasColumnType("TEXT");

                    b.Property<string>("FilterColumn")
                        .HasColumnType("TEXT");

                    b.Property<int?>("FilterTime")
                        .HasColumnType("INTEGER");

                    b.Property<string>("HeaderStructure")
                        .HasColumnType("TEXT");

                    b.Property<string>("HttpMethod")
                        .HasColumnType("TEXT");

                    b.Property<string>("IndexName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<bool>("IsIncremental")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("IsVirtual")
                        .HasColumnType("INTEGER");

                    b.Property<bool?>("IsVirtualTemplate")
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "extractionName");

                    b.Property<string>("OffsetAttr")
                        .HasColumnType("TEXT");

                    b.Property<string>("OffsetLimitAttr")
                        .HasColumnType("TEXT");

                    b.Property<uint>("OriginId")
                        .HasColumnType("INTEGER");

                    b.Property<string>("OverrideQuery")
                        .HasColumnType("TEXT");

                    b.Property<string>("PageAttr")
                        .HasColumnType("TEXT");

                    b.Property<uint?>("ScheduleId")
                        .HasColumnType("INTEGER");

                    b.Property<bool>("SingleExecution")
                        .HasColumnType("INTEGER");

                    b.Property<string>("TotalPageAttr")
                        .HasColumnType("TEXT");

                    b.Property<string>("VirtualId")
                        .HasColumnType("TEXT");

                    b.Property<string>("VirtualIdGroup")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.HasIndex("DestinationId");

                    b.HasIndex("OriginId");

                    b.HasIndex("ScheduleId");

                    b.ToTable("EXTRACTIONS");
                });

            modelBuilder.Entity("Conductor.Model.Job", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<long>("BytesAccumulated")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime?>("EndTime")
                        .HasColumnType("TEXT");

                    b.PrimitiveCollection<string>("ExtractionIds")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<Guid>("JobGuid")
                        .HasColumnType("TEXT");

                    b.Property<int>("JobType")
                        .HasColumnType("INTEGER");

                    b.Property<DateTime>("StartTime")
                        .HasColumnType("TEXT");

                    b.Property<int>("Status")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("JOBS");
                });

            modelBuilder.Entity("Conductor.Model.Origin", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Alias")
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "originAlias");

                    b.Property<string>("ConnectionString")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "originConStr");

                    b.Property<string>("DbType")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "originDbType");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "originName");

                    b.Property<double>("TimeZoneOffSet")
                        .HasColumnType("REAL")
                        .HasAnnotation("Relational:JsonPropertyName", "originTimeZoneOffSet");

                    b.HasKey("Id");

                    b.ToTable("ORIGINS");
                });

            modelBuilder.Entity("Conductor.Model.Record", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("CallerMethod")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("Event")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("EventType")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<string>("HostName")
                        .IsRequired()
                        .HasColumnType("TEXT");

                    b.Property<DateTime>("TimeStamp")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("RECORDS");
                });

            modelBuilder.Entity("Conductor.Model.Schedule", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "scheduleName");

                    b.Property<bool>("Status")
                        .HasColumnType("INTEGER");

                    b.Property<int>("Value")
                        .HasColumnType("INTEGER");

                    b.HasKey("Id");

                    b.ToTable("SCHEDULES");
                });

            modelBuilder.Entity("Conductor.Model.User", b =>
                {
                    b.Property<uint>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("TEXT")
                        .HasAnnotation("Relational:JsonPropertyName", "username");

                    b.Property<string>("Password")
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("USERS");
                });

            modelBuilder.Entity("Conductor.Model.Extraction", b =>
                {
                    b.HasOne("Conductor.Model.Destination", "Destination")
                        .WithMany()
                        .HasForeignKey("DestinationId");

                    b.HasOne("Conductor.Model.Origin", "Origin")
                        .WithMany()
                        .HasForeignKey("OriginId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("Conductor.Model.Schedule", "Schedule")
                        .WithMany()
                        .HasForeignKey("ScheduleId");

                    b.Navigation("Destination");

                    b.Navigation("Origin");

                    b.Navigation("Schedule");
                });
#pragma warning restore 612, 618
        }
    }
}
