name: Docker Package CI

on:
  push:
    tags:
      - "docker-v*"
  workflow_dispatch:

permissions:
  contents: read
  packages: write 

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4

    - name: Set Version Number
      run: echo "VERSION=${GITHUB_REF#refs/tags/}" >> $GITHUB_ENV

    - name: Log in to GitHub Container Registry
      run: echo "${{ secrets.GITHUB_TOKEN }}" | docker login ghcr.io -u $GITHUB_ACTOR --password-stdin

    - name: Build the Docker image
      run: docker build . --file ./docker/main/Dockerfile --tag ghcr.io/${{ github.repository_owner }}/conductor:$VERSION

    - name: Push to GitHub Container Registry
      run: docker push ghcr.io/${{ github.repository_owner }}/conductor:$VERSION
